export const ALARM_PERIODS = {
  morning: {
    id: 'morning',
    name: '아침 루틴',
    icon: '🌅',
    gradient: 'linear-gradient(135deg, #F6D365 0%, #FDA085 100%)',
    color: '#E67E22',
    darkText: true,
    defaultTime: '07:30',
    defaultDays: [0, 1, 2, 3, 4, 5, 6],
    behaviors: [
      {
        id: 'sunlight',
        title: '햇빛 보기',
        desc: '아침 햇빛이 생체시계를 조절하고 기분을 높여줍니다',
        tip: '커튼을 열거나 베란다에 잠깐 나가보세요',
      },
      {
        id: 'water',
        title: '물 마시기',
        desc: '기상 후 물 한 잔으로 신진대사를 깨워보세요',
        tip: '미지근한 물 250ml를 천천히 마셔보세요',
      },
      {
        id: 'stretch',
        title: '스트레칭',
        desc: '5분 스트레칭으로 몸을 깨우고 혈액순환을 돕습니다',
        tip: '목·어깨·허리 순서로 부드럽게 풀어주세요',
      },
    ],
  },
  afternoon: {
    id: 'afternoon',
    name: '오후 루틴',
    icon: '☀️',
    gradient: 'linear-gradient(135deg, #43E97B 0%, #38F9D7 100%)',
    color: '#00B894',
    darkText: true,
    defaultTime: '13:30',
    defaultDays: [0, 1, 2, 3, 4, 5, 6],
    behaviors: [
      {
        id: 'walk',
        title: '짧은 산책',
        desc: '점심 후 10분 산책은 소화와 오후 집중력에 도움이 됩니다',
        tip: '사무실 주변이나 계단을 이용해보세요',
      },
      {
        id: 'stretch',
        title: '스트레칭',
        desc: '앉아 있어 굳어진 몸을 잠깐 풀어주세요',
        tip: '손목·목·등을 가볍게 풀어주세요',
      },
      {
        id: 'eye_rest',
        title: '눈 휴식',
        desc: '20-20-20 규칙으로 눈 피로를 줄여보세요',
        tip: '20분마다 20초간 6m 앞을 바라보세요',
      },
    ],
  },
  evening: {
    id: 'evening',
    name: '저녁 루틴',
    icon: '🌆',
    gradient: 'linear-gradient(135deg, #6C5CE7 0%, #a29bfe 100%)',
    color: '#6C5CE7',
    defaultTime: '18:30',
    defaultDays: [1, 2, 3, 4, 5],
    behaviors: [
      {
        id: 'exercise',
        title: '운동하기',
        desc: '저녁 가벼운 운동이 수면의 질을 높여줍니다',
        tip: '30분 걷기나 가벼운 스트레칭으로 시작해보세요',
      },
      {
        id: 'dinner',
        title: '저녁 식사',
        desc: '규칙적인 저녁 식사 시간이 몸의 리듬을 잡아줍니다',
        tip: '취침 3시간 전에 식사를 마치면 좋아요',
      },
      {
        id: 'digest',
        title: '소화 돕기',
        desc: '식후 가벼운 활동이 소화를 도와줍니다',
        tip: '짧은 산책이나 가벼운 집안일을 해보세요',
      },
    ],
  },
  bedtime: {
    id: 'bedtime',
    name: '취침 준비',
    icon: '🌙',
    gradient: 'linear-gradient(135deg, #2C3E50 0%, #4CA1AF 100%)',
    color: '#2C3E50',
    defaultTime: '22:30',
    defaultDays: [0, 1, 2, 3, 4, 5, 6],
    behaviors: [
      {
        id: 'dim_lights',
        title: '조명 줄이기',
        desc: '취침 1시간 전 조명을 줄이면 멜라토닌 분비를 돕습니다',
        tip: '스탠드나 간접 조명으로 전환해보세요',
      },
      {
        id: 'no_phone',
        title: '핸드폰 끄기',
        desc: '블루라이트 차단이 숙면에 도움이 됩니다',
        tip: '취침 30분 전 핸드폰을 내려놓고 책을 읽어보세요',
      },
      {
        id: 'sleep_prep',
        title: '수면 준비',
        desc: '몸과 마음을 이완시켜 좋은 잠을 준비하세요',
        tip: '따뜻한 샤워나 가벼운 스트레칭을 해보세요',
      },
    ],
  },
}

export const PERIOD_ORDER = ['morning', 'afternoon', 'evening', 'bedtime']

// 베타 테스트용 시간별 행동양식 (7시~23시)
// timerSeconds: 타이머 기반 실천 권장 시간 (null이면 즉시 완료만)
export const TEST_HOURLY_BEHAVIORS = {
  '07': { id: 'test_07', title: '기상 후 물 한 잔 마시기',    timerSeconds: 10,  desc: '자는 동안 부족해진 수분을 채워 신체를 깨워요', tip: '미지근한 물 한 컵이면 충분해요' },
  '08': { id: 'test_08', title: '햇빛 5분 쬐기',              timerSeconds: 300, desc: '아침 햇빛은 생체리듬을 조절하고 각성도를 높여요', tip: '창가나 베란다에서 잠깐이면 돼요' },
  '09': { id: 'test_09', title: '목·어깨 가볍게 풀기',        timerSeconds: 45,  desc: '굳어있던 목과 어깨를 풀어 긴장을 낮춰요', tip: '천천히 원을 그리듯 돌려주세요' },
  '10': { id: 'test_10', title: '눈 감고 1분 휴식',           timerSeconds: 60,  desc: '짧은 눈 감기로 시신경의 피로를 줄여요', tip: '화면에서 눈을 떼고 편하게 감아보세요' },
  '11': { id: 'test_11', title: '허리 펴고 자세 교정하기',    timerSeconds: 30,  desc: '굽어진 자세를 바로잡아 척추 부담을 줄여요', tip: '어깨를 뒤로, 배에 살짝 힘을 줘보세요' },
  '12': { id: 'test_12', title: '점심 전 물 한 컵 마시기',   timerSeconds: 10,  desc: '식사 전 수분 보충으로 소화를 도와요', tip: '물 한 컵을 천천히 마셔보세요' },
  '13': { id: 'test_13', title: '짧게 눈 붙이기 (파워냅)',   timerSeconds: 600, desc: '짧은 낮잠은 오후 집중력 회복에 효과적이에요', tip: '10분을 넘기지 않는 게 개운해요' },
  '14': { id: 'test_14', title: '가볍게 5분 걷기',            timerSeconds: 300, desc: '짧은 걷기로 혈액순환과 각성도를 높여요', tip: '사무실 복도나 계단도 좋아요' },
  '15': { id: 'test_15', title: '전신 스트레칭',              timerSeconds: 60,  desc: '신체 활성도가 높아지는 시간, 스트레칭으로 컨디션을 올려요', tip: '팔다리를 쭉 늘려주세요' },
  '16': { id: 'test_16', title: '심호흡하기',                 timerSeconds: 30,  desc: '깊은 호흡으로 긴장을 낮추고 마음을 가다듬어요', tip: '4초 들이쉬고 6초 내쉬어보세요' },
  '17': { id: 'test_17', title: '물 한 컵 먼저 마시기',      timerSeconds: 10,  desc: '식욕이 오르는 시간, 물로 먼저 신호를 조절해요', tip: '간식 전에 물 한 잔이면 충분해요' },
  '18': { id: 'test_18', title: '가벼운 운동 10분',           timerSeconds: 600, desc: '신체 활동 능력이 가장 좋은 시간, 가볍게 움직여요', tip: '무리하지 않는 강도로 시작해보세요' },
  '19': { id: 'test_19', title: '느린 호흡 6회',             timerSeconds: 60,  desc: '저녁 긴장을 낮추는 느린 호흡으로 이완해요', tip: '4초 들숨, 6초 날숨을 6번 반복해요' },
  '20': { id: 'test_20', title: '식후 가볍게 걷기',           timerSeconds: 300, desc: '식후 걷기는 소화를 돕고 나른함을 줄여요', tip: '5~10분이면 충분해요' },
  '21': { id: 'test_21', title: '조명 낮추고 스트레칭',       timerSeconds: 60,  desc: '조명을 낮춰 수면 준비 신호를 보내요', tip: '가볍게 몸을 풀며 마무리해요' },
  '22': { id: 'test_22', title: '천천히 호흡하며 이완하기',   timerSeconds: 60,  desc: '부교감신경을 활성화해 몸을 이완시켜요', tip: '어깨 힘을 빼고 천천히 숨쉬어보세요' },
  '23': { id: 'test_23', title: '화면 끄고 조용히 눈 감기',  timerSeconds: 300, desc: '화면 자극을 줄여 수면 준비를 도와요', tip: '휴대폰은 잠시 내려두세요' },
}

// Returns custom behaviors if set, otherwise falls back to defaults
export function getEffectiveBehaviors(periodId, customBehaviors) {
  return customBehaviors?.[periodId] ?? ALARM_PERIODS[periodId]?.behaviors ?? []
}

// ─── 시간대별 행동 원리 가이드 ─────────────────────────────────────────────────
// 23~05시: 수면 블록 / 06~22시: 1시간 단위
export const TIME_PERIOD_GUIDES = [
  {
    hours: [23, 0, 1, 2, 3, 4, 5],
    title: '숙면 타임',
    icon: '🌙',
    gradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    darkText: false,
    headline: '어둡고 서늘하게, 몸과 뇌를 회복해요',
    body: '숙면을 위해 어둡고 서늘한 환경을 유지하세요. 깊은 수면 중에 성장호르몬이 분비되고 뇌의 노폐물이 제거되어 몸과 뇌가 회복됩니다.',
    tip: '😴 실내 온도 18~20°C, 핸드폰은 침대 밖에 두세요.',
  },
  {
    hours: [6],
    title: '오전 6시',
    icon: '🌅',
    gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    darkText: true,
    headline: '기상 직후 물 한 잔 & 햇빛으로 생체리듬 활성화',
    body: '기상 후 물 한 잔은 수면 중 빠진 수분을 보충하고 신진대사를 깨웁니다. 햇빛이 눈에 닿으면 생체시계가 리셋되어 하루 리듬이 안정됩니다.',
    tip: '🥛 미지근한 물 250ml → 창가에서 햇빛 10분 쬐기',
  },
  {
    hours: [7],
    title: '오전 7시',
    icon: '🤸',
    gradient: 'linear-gradient(135deg, #F6D365 0%, #FDA085 100%)',
    darkText: true,
    headline: '가벼운 스트레칭으로 몸 깨우기',
    body: '수면 중 굳어진 근육을 5~10분 스트레칭으로 풀어주세요. 단백질 위주 아침 식사는 포만감을 오래 유지시켜 오전 집중력을 높여줍니다.',
    tip: '🧘 목·어깨·허리 스트레칭 → 달걀·두부 등 단백질 식사 준비',
  },
  {
    hours: [8],
    title: '오전 8시',
    icon: '🍳',
    gradient: 'linear-gradient(135deg, #f9ca24 0%, #f0932b 100%)',
    darkText: true,
    headline: '아침 식사 & 하루 계획 정리',
    body: '아침 식사는 뇌와 근육에 에너지를 공급합니다. 식사 후 오늘의 핵심 목표 3가지를 메모해두면 하루를 더 주도적으로 시작할 수 있습니다.',
    tip: '📋 오늘 반드시 해야 할 일 3가지를 메모해두세요.',
  },
  {
    hours: [9],
    title: '오전 9시',
    icon: '🧠',
    gradient: 'linear-gradient(135deg, #6a11cb 0%, #2575fc 100%)',
    darkText: false,
    headline: '집중력 상승 구간, 중요한 업무·학습 우선 처리',
    body: '코르티솔이 최고조에 오르는 오전 9시는 인지 능력과 집중력이 빠르게 올라가는 시간입니다. 가장 중요하고 어려운 일을 먼저 처리하세요.',
    tip: '📵 알림을 끄고 중요 업무부터 시작하세요.',
  },
  {
    hours: [10],
    title: '오전 10시',
    icon: '⚡',
    gradient: 'linear-gradient(135deg, #4776e6 0%, #8e54e9 100%)',
    darkText: false,
    headline: '오전 집중 피크, 어려운 과제 처리하기 좋은 시간',
    body: '도파민·세로토닌·코르티솔이 함께 높아지는 이 시간은 하루 중 인지 능력이 가장 뛰어난 구간입니다. 창의적 사고와 복잡한 문제 해결에 집중하세요.',
    tip: '🎯 가장 도전적인 과제를 이 시간에 배치하세요.',
  },
  {
    hours: [11],
    title: '오전 11시',
    icon: '💧',
    gradient: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
    darkText: false,
    headline: '점심 전 가벼운 움직임 & 수분 보충',
    body: '오전 내내 집중한 뇌와 몸에 수분을 보충하세요. 2~3분 스트레칭과 물 한 컵으로 오전 마지막 집중력을 끌어올릴 수 있습니다.',
    tip: '💧 물 한 컵 + 자리에서 일어나 2분 스트레칭',
  },
  {
    hours: [12],
    title: '오후 12시',
    icon: '🥗',
    gradient: 'linear-gradient(135deg, #43E97B 0%, #38F9D7 100%)',
    darkText: true,
    headline: '균형 잡힌 점심 식사, 과식은 피하기',
    body: '과식하면 소화에 혈류가 집중되어 오후 졸음이 심해집니다. 채소·단백질·복합탄수화물을 고루 먹고 80% 정도 포만감에서 멈추세요.',
    tip: '🥢 천천히 씹어 먹고 80% 포만감에서 수저를 내려두세요.',
  },
  {
    hours: [13],
    title: '오후 1시',
    icon: '🚶',
    gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    darkText: true,
    headline: '식후 가벼운 산책 & 짧은 휴식',
    body: '식후 10분 걷기는 혈당 스파이크를 30% 낮춰 오후 집중력을 지켜줍니다. 짧은 휴식으로 소화를 돕고 오후 업무를 준비하세요.',
    tip: '🚶 10분 산책 후 짧은 휴식으로 오후를 준비하세요.',
  },
  {
    hours: [14],
    title: '오후 2시',
    icon: '😴',
    gradient: 'linear-gradient(135deg, #f7971e 0%, #f5576c 100%)',
    darkText: false,
    headline: '식후 졸음 주의, 짧은 낮잠(10~20분) 추천',
    body: '오후 2시는 생체리듬상 체온이 일시적으로 떨어지며 졸음이 몰려오는 시간입니다. 10~20분 낮잠은 이후 집중력을 크게 회복시켜 줍니다.',
    tip: '💤 알람 20분 맞추고 짧은 낮잠 — 30분 이상은 오히려 역효과!',
  },
  {
    hours: [15],
    title: '오후 3시',
    icon: '✨',
    gradient: 'linear-gradient(135deg, #ee0979 0%, #ff6a00 100%)',
    darkText: false,
    headline: '두 번째 집중력 피크, 창의적 작업하기 좋은 시간',
    body: '낮잠이나 휴식 후 체온이 다시 오르며 두 번째 집중 구간이 찾아옵니다. 브레인스토밍, 기획, 글쓰기 등 창의적인 작업에 적합합니다.',
    tip: '💡 아이디어 정리, 기획서 작성, 창의 작업을 이 시간에 해보세요.',
  },
  {
    hours: [16],
    title: '오후 4시',
    icon: '🏃',
    gradient: 'linear-gradient(135deg, #f46b45 0%, #eea849 100%)',
    darkText: true,
    headline: '운동하기 가장 좋은 시간, 체온과 근력이 최고조',
    body: '오후 4~5시는 체온·근력·유연성·반응속도가 모두 최고조에 달합니다. 이 시간대 운동은 같은 노력으로 더 높은 퍼포먼스를 낼 수 있습니다.',
    tip: '🏋️ 유산소든 근력이든 오늘 운동은 지금 시작하세요!',
  },
  {
    hours: [17],
    title: '오후 5시',
    icon: '📋',
    gradient: 'linear-gradient(135deg, #c94b4b 0%, #4b134f 100%)',
    darkText: false,
    headline: '하루 업무 마무리 & 내일 할 일 정리',
    body: '퇴근 전 오늘 완료한 일을 체크하고 내일 핵심 과제 3가지를 미리 적어두면 퇴근 후 불안이 줄고 내일 아침을 더 수월하게 시작할 수 있습니다.',
    tip: '📝 오늘 완료 체크 → 내일 TOP 3 메모 후 마음 편히 퇴근!',
  },
  {
    hours: [18],
    title: '오후 6시',
    icon: '🍽️',
    gradient: 'linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)',
    darkText: true,
    headline: '저녁 식사, 가볍게 먹기',
    body: '취침 3시간 전에 저녁 식사를 마쳐야 수면 중 소화 부담이 없습니다. 가볍게 먹을수록 수면의 질이 높아지고 다음 날 아침이 상쾌해집니다.',
    tip: '🕙 취침 3시간 전 식사 마무리 — 늦은 야식은 수면의 적!',
  },
  {
    hours: [19],
    title: '오후 7시',
    icon: '🌿',
    gradient: 'linear-gradient(135deg, #6C5CE7 0%, #a29bfe 100%)',
    darkText: false,
    headline: '소화를 위한 가벼운 산책, 몸과 마음 이완',
    body: '저녁 식사 후 15~20분 걷기는 소화를 돕고 저녁 혈당을 안정시킵니다. 자연 속 또는 조용한 거리를 걸으면 하루의 스트레스도 함께 해소됩니다.',
    tip: '🚶 저녁 산책 15~20분으로 소화와 이완을 동시에!',
  },
  {
    hours: [20],
    title: '오후 8시',
    icon: '📚',
    gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    darkText: true,
    headline: '독서나 가벼운 취미 활동, 자기계발 시간',
    body: '멜라토닌 분비가 시작되는 이 시간에 화면 대신 독서나 취미를 즐기면 수면 준비가 자연스럽게 됩니다. 자기계발과 수면 질 향상을 동시에 얻을 수 있습니다.',
    tip: '📖 핸드폰 대신 책 20분 — 수면 질이 눈에 띄게 달라져요.',
  },
  {
    hours: [21],
    title: '오후 9시',
    icon: '🔅',
    gradient: 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
    darkText: false,
    headline: '블루라이트 줄이기, 수면 준비 루틴 시작',
    body: '블루라이트는 멜라토닌 분비를 억제해 수면을 방해합니다. 이 시간부터 화면 밝기를 낮추거나 야간 모드를 켜고 수면 루틴을 시작하세요.',
    tip: '📵 야간 모드 ON + 화면 밝기 최소화, 스트레칭 또는 명상 시작',
  },
  {
    hours: [22],
    title: '오후 10시',
    icon: '🌛',
    gradient: 'linear-gradient(135deg, #2C3E50 0%, #4CA1AF 100%)',
    darkText: false,
    headline: '내일 준비 마무리, 조명 어둡게 하고 마음 정리',
    body: '내일 필요한 것을 미리 준비하고 간접 조명만 켜두세요. 취침 전 감사한 일 3가지를 떠올리면 마음이 편해지고 수면의 질도 높아집니다.',
    tip: '💡 간접 조명만 켜기 → 내일 준비 → 감사한 일 3가지 떠올리기',
  },
]

export function getCurrentPeriodGuide(hour) {
  return TIME_PERIOD_GUIDES.find(g => g.hours.includes(hour)) ?? null
}
